# Generated by Django 6.1.1 on 2026-10-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_slug_3edc0c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=600, null=True, upload_to='products/'),
        ),
    ]
